// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutor2019.Apps.DockerWebMvc.Data.Entity.Db;

namespace Tutor2019.Apps.DockerWebMvc.Migrations
{
    [DbContext(typeof(DataEntityDbContext))]
    partial class DataEntityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tutor2019.Apps.DockerWebMvc.Data.Entity.Objects.DataEntityObjectProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<decimal>("Price");

                    b.HasKey("Id")
                        .HasName("PK_Product");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Category-3",
                            Name = "Name-1",
                            Price = 1001.01m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Category-8",
                            Name = "Name-2",
                            Price = 1002.02m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Category-3",
                            Name = "Name-3",
                            Price = 1003.03m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Category-3",
                            Name = "Name-4",
                            Price = 1004.04m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Category-2",
                            Name = "Name-5",
                            Price = 1005.05m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Category-4",
                            Name = "Name-6",
                            Price = 1006.06m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Category-1",
                            Name = "Name-7",
                            Price = 1007.07m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Category-6",
                            Name = "Name-8",
                            Price = 1008.08m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Category-9",
                            Name = "Name-9",
                            Price = 1009.09m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Category-4",
                            Name = "Name-10",
                            Price = 1010.1m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Category-2",
                            Name = "Name-11",
                            Price = 1011.11m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Category-3",
                            Name = "Name-12",
                            Price = 1012.12m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Category-6",
                            Name = "Name-13",
                            Price = 1013.13m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Category-2",
                            Name = "Name-14",
                            Price = 1014.14m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Category-9",
                            Name = "Name-15",
                            Price = 1015.15m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Category-2",
                            Name = "Name-16",
                            Price = 1016.16m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Category-6",
                            Name = "Name-17",
                            Price = 1017.17m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Category-4",
                            Name = "Name-18",
                            Price = 1018.18m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Category-7",
                            Name = "Name-19",
                            Price = 1019.19m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Category-1",
                            Name = "Name-20",
                            Price = 1020.2m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Category-1",
                            Name = "Name-21",
                            Price = 1021.21m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Category-1",
                            Name = "Name-22",
                            Price = 1022.22m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Category-4",
                            Name = "Name-23",
                            Price = 1023.23m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Category-8",
                            Name = "Name-24",
                            Price = 1024.24m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Category-2",
                            Name = "Name-25",
                            Price = 1025.25m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Category-7",
                            Name = "Name-26",
                            Price = 1026.26m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Category-6",
                            Name = "Name-27",
                            Price = 1027.27m
                        },
                        new
                        {
                            Id = 28,
                            Category = "Category-1",
                            Name = "Name-28",
                            Price = 1028.28m
                        },
                        new
                        {
                            Id = 29,
                            Category = "Category-6",
                            Name = "Name-29",
                            Price = 1029.29m
                        },
                        new
                        {
                            Id = 30,
                            Category = "Category-7",
                            Name = "Name-30",
                            Price = 1030.3m
                        },
                        new
                        {
                            Id = 31,
                            Category = "Category-4",
                            Name = "Name-31",
                            Price = 1031.31m
                        },
                        new
                        {
                            Id = 32,
                            Category = "Category-3",
                            Name = "Name-32",
                            Price = 1032.32m
                        },
                        new
                        {
                            Id = 33,
                            Category = "Category-7",
                            Name = "Name-33",
                            Price = 1033.33m
                        },
                        new
                        {
                            Id = 34,
                            Category = "Category-8",
                            Name = "Name-34",
                            Price = 1034.34m
                        },
                        new
                        {
                            Id = 35,
                            Category = "Category-5",
                            Name = "Name-35",
                            Price = 1035.35m
                        },
                        new
                        {
                            Id = 36,
                            Category = "Category-9",
                            Name = "Name-36",
                            Price = 1036.36m
                        },
                        new
                        {
                            Id = 37,
                            Category = "Category-2",
                            Name = "Name-37",
                            Price = 1037.37m
                        },
                        new
                        {
                            Id = 38,
                            Category = "Category-5",
                            Name = "Name-38",
                            Price = 1038.38m
                        },
                        new
                        {
                            Id = 39,
                            Category = "Category-5",
                            Name = "Name-39",
                            Price = 1039.39m
                        },
                        new
                        {
                            Id = 40,
                            Category = "Category-5",
                            Name = "Name-40",
                            Price = 1040.4m
                        },
                        new
                        {
                            Id = 41,
                            Category = "Category-1",
                            Name = "Name-41",
                            Price = 1041.41m
                        },
                        new
                        {
                            Id = 42,
                            Category = "Category-3",
                            Name = "Name-42",
                            Price = 1042.42m
                        },
                        new
                        {
                            Id = 43,
                            Category = "Category-4",
                            Name = "Name-43",
                            Price = 1043.43m
                        },
                        new
                        {
                            Id = 44,
                            Category = "Category-1",
                            Name = "Name-44",
                            Price = 1044.44m
                        },
                        new
                        {
                            Id = 45,
                            Category = "Category-6",
                            Name = "Name-45",
                            Price = 1045.45m
                        },
                        new
                        {
                            Id = 46,
                            Category = "Category-3",
                            Name = "Name-46",
                            Price = 1046.46m
                        },
                        new
                        {
                            Id = 47,
                            Category = "Category-5",
                            Name = "Name-47",
                            Price = 1047.47m
                        },
                        new
                        {
                            Id = 48,
                            Category = "Category-4",
                            Name = "Name-48",
                            Price = 1048.48m
                        },
                        new
                        {
                            Id = 49,
                            Category = "Category-2",
                            Name = "Name-49",
                            Price = 1049.49m
                        },
                        new
                        {
                            Id = 50,
                            Category = "Category-5",
                            Name = "Name-50",
                            Price = 1050.5m
                        },
                        new
                        {
                            Id = 51,
                            Category = "Category-8",
                            Name = "Name-51",
                            Price = 1051.51m
                        },
                        new
                        {
                            Id = 52,
                            Category = "Category-7",
                            Name = "Name-52",
                            Price = 1052.52m
                        },
                        new
                        {
                            Id = 53,
                            Category = "Category-1",
                            Name = "Name-53",
                            Price = 1053.53m
                        },
                        new
                        {
                            Id = 54,
                            Category = "Category-1",
                            Name = "Name-54",
                            Price = 1054.54m
                        },
                        new
                        {
                            Id = 55,
                            Category = "Category-6",
                            Name = "Name-55",
                            Price = 1055.55m
                        },
                        new
                        {
                            Id = 56,
                            Category = "Category-6",
                            Name = "Name-56",
                            Price = 1056.56m
                        },
                        new
                        {
                            Id = 57,
                            Category = "Category-2",
                            Name = "Name-57",
                            Price = 1057.57m
                        },
                        new
                        {
                            Id = 58,
                            Category = "Category-9",
                            Name = "Name-58",
                            Price = 1058.58m
                        },
                        new
                        {
                            Id = 59,
                            Category = "Category-3",
                            Name = "Name-59",
                            Price = 1059.59m
                        },
                        new
                        {
                            Id = 60,
                            Category = "Category-4",
                            Name = "Name-60",
                            Price = 1060.6m
                        },
                        new
                        {
                            Id = 61,
                            Category = "Category-6",
                            Name = "Name-61",
                            Price = 1061.61m
                        },
                        new
                        {
                            Id = 62,
                            Category = "Category-2",
                            Name = "Name-62",
                            Price = 1062.62m
                        },
                        new
                        {
                            Id = 63,
                            Category = "Category-4",
                            Name = "Name-63",
                            Price = 1063.63m
                        },
                        new
                        {
                            Id = 64,
                            Category = "Category-4",
                            Name = "Name-64",
                            Price = 1064.64m
                        },
                        new
                        {
                            Id = 65,
                            Category = "Category-7",
                            Name = "Name-65",
                            Price = 1065.65m
                        },
                        new
                        {
                            Id = 66,
                            Category = "Category-3",
                            Name = "Name-66",
                            Price = 1066.66m
                        },
                        new
                        {
                            Id = 67,
                            Category = "Category-5",
                            Name = "Name-67",
                            Price = 1067.67m
                        },
                        new
                        {
                            Id = 68,
                            Category = "Category-7",
                            Name = "Name-68",
                            Price = 1068.68m
                        },
                        new
                        {
                            Id = 69,
                            Category = "Category-8",
                            Name = "Name-69",
                            Price = 1069.69m
                        },
                        new
                        {
                            Id = 70,
                            Category = "Category-6",
                            Name = "Name-70",
                            Price = 1070.7m
                        },
                        new
                        {
                            Id = 71,
                            Category = "Category-7",
                            Name = "Name-71",
                            Price = 1071.71m
                        },
                        new
                        {
                            Id = 72,
                            Category = "Category-9",
                            Name = "Name-72",
                            Price = 1072.72m
                        },
                        new
                        {
                            Id = 73,
                            Category = "Category-8",
                            Name = "Name-73",
                            Price = 1073.73m
                        },
                        new
                        {
                            Id = 74,
                            Category = "Category-2",
                            Name = "Name-74",
                            Price = 1074.74m
                        },
                        new
                        {
                            Id = 75,
                            Category = "Category-6",
                            Name = "Name-75",
                            Price = 1075.75m
                        },
                        new
                        {
                            Id = 76,
                            Category = "Category-1",
                            Name = "Name-76",
                            Price = 1076.76m
                        },
                        new
                        {
                            Id = 77,
                            Category = "Category-5",
                            Name = "Name-77",
                            Price = 1077.77m
                        },
                        new
                        {
                            Id = 78,
                            Category = "Category-7",
                            Name = "Name-78",
                            Price = 1078.78m
                        },
                        new
                        {
                            Id = 79,
                            Category = "Category-6",
                            Name = "Name-79",
                            Price = 1079.79m
                        },
                        new
                        {
                            Id = 80,
                            Category = "Category-7",
                            Name = "Name-80",
                            Price = 1080.8m
                        },
                        new
                        {
                            Id = 81,
                            Category = "Category-1",
                            Name = "Name-81",
                            Price = 1081.81m
                        },
                        new
                        {
                            Id = 82,
                            Category = "Category-6",
                            Name = "Name-82",
                            Price = 1082.82m
                        },
                        new
                        {
                            Id = 83,
                            Category = "Category-3",
                            Name = "Name-83",
                            Price = 1083.83m
                        },
                        new
                        {
                            Id = 84,
                            Category = "Category-6",
                            Name = "Name-84",
                            Price = 1084.84m
                        },
                        new
                        {
                            Id = 85,
                            Category = "Category-4",
                            Name = "Name-85",
                            Price = 1085.85m
                        },
                        new
                        {
                            Id = 86,
                            Category = "Category-7",
                            Name = "Name-86",
                            Price = 1086.86m
                        },
                        new
                        {
                            Id = 87,
                            Category = "Category-5",
                            Name = "Name-87",
                            Price = 1087.87m
                        },
                        new
                        {
                            Id = 88,
                            Category = "Category-5",
                            Name = "Name-88",
                            Price = 1088.88m
                        },
                        new
                        {
                            Id = 89,
                            Category = "Category-7",
                            Name = "Name-89",
                            Price = 1089.89m
                        },
                        new
                        {
                            Id = 90,
                            Category = "Category-8",
                            Name = "Name-90",
                            Price = 1090.9m
                        },
                        new
                        {
                            Id = 91,
                            Category = "Category-3",
                            Name = "Name-91",
                            Price = 1091.91m
                        },
                        new
                        {
                            Id = 92,
                            Category = "Category-5",
                            Name = "Name-92",
                            Price = 1092.92m
                        },
                        new
                        {
                            Id = 93,
                            Category = "Category-8",
                            Name = "Name-93",
                            Price = 1093.93m
                        },
                        new
                        {
                            Id = 94,
                            Category = "Category-5",
                            Name = "Name-94",
                            Price = 1094.94m
                        },
                        new
                        {
                            Id = 95,
                            Category = "Category-8",
                            Name = "Name-95",
                            Price = 1095.95m
                        },
                        new
                        {
                            Id = 96,
                            Category = "Category-1",
                            Name = "Name-96",
                            Price = 1096.96m
                        },
                        new
                        {
                            Id = 97,
                            Category = "Category-6",
                            Name = "Name-97",
                            Price = 1097.97m
                        },
                        new
                        {
                            Id = 98,
                            Category = "Category-6",
                            Name = "Name-98",
                            Price = 1098.98m
                        },
                        new
                        {
                            Id = 99,
                            Category = "Category-9",
                            Name = "Name-99",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 100,
                            Category = "Category-8",
                            Name = "Name-100",
                            Price = 1101m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
